# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32c2977ba55b496a7327b7bd3bd8d2d3f917e808f36f2067758c93efd6b9ff0a4aefed640671488feec64bec9684ad1d25c0987539c19f75be0b150a4235f899

test:
  secret_key_base: 03b1fb1d99e873f624ceed3e8dd0f0aa870e8daa7a7f58e2fcacf1b663efe4328112628e5889252a226c51294a1fc8d6f42165432e1e3b786165951ca9fdb6d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
